<a href="https://colab.research.google.com/github/mukul2508/UCS420_MUKUL-_BANSAL_1024170294/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd

roll_num=input("enter your roll number: ")
last2=[roll_num[-2:]]
categories=["billing","account","general"]

fixed_entries = [
 {"question": "what is the annual fee",
  "answer": "The annual fee is Rs 500.",
 "keywords": "fee cost price charge",
  "category": "billing"},

 {"question": "how to reset password",
  "answer": "Go to Settings > Reset Password.",
 "keywords": "password reset login",
  "category": "account"},

 {"question": "what are your working hours",
  "answer": "We are open 9 AM to 5 PM.",
 "keywords": "hours timing open time",
  "category": "general"},

 {"question": "how can i pay the fee",
  "answer": "You can pay via UPI, card, or net banking.",
 "keywords": "pay payment upi fee",
  "category": "billing"},
]

new_entries=[]
for digit in last2:
  d=int(digit)
  category=categories[d%3];

  if category == "billing":
        question = "how can I check my fee payment status"
        answer = "You can check your fee payment status in the payment section."
        keywords = "fee payment status billing"

  elif category == "account":
        question = "how do I update my registered mobile number"
        answer = "You can update your registered mobile number from account settings."
        keywords = "mobile number account update"

  else:
        question = "what documents are required for registration"
        answer = "You need your college ID and required registration documents."
        keywords = "documents registration general"

  new_entries.append({
    "question":question,
    "answer":answer,
    "keywords":keywords,
    "category":category
  })

all_entries=fixed_entries+new_entries
df=pd.DataFrame(all_entries)
df

enter your roll number: 1024170294

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,how do i update my registered mobile number,You can update your registered mobile number f...,mobile number account update,account

In [5]:
import numpy as np
def scoring(query,df):
  questions = [sent.lower().split() for sent in df['question']]
  actual = query.lower().split()
  order = []
  for i in range(len(questions)):
    cnt = 0
    for w in actual:
      if(w in questions[i]):
        cnt+=1
    order.append(cnt)
  sorted_order = np.argsort(order)
  ans =[]
  for i in range(len(order)):
    ans.append(df['question'][sorted_order[i]])
  return ans

print("Please enter a query")
query = input()
ranked_FAQ = scoring(query,df)
print("Here are FAQ's in sorted order -> (increasing order of matching)")
print(ranked_FAQ)

Please enter a query
change my email
Here are FAQ's in sorted order -> (increasing order of matching)
['what is the annual fee', 'how to reset password', 'what are your working hours', 'how can i pay the fee', 'how do i update my registered mobile number']

In [6]:

def same_category(category_name, df):
    return df[df["category"] == category_name]

category_name = "billing"
result = same_category(category_name, df)

print("FAQs belonging to category:", category_name)
result

FAQs belonging to category: billing

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing

In [7]:
index = 0

new_keyword = input("Enter new keyword: ")

df.loc[index, "keywords"] = df.loc[index, "keywords"] + " " + new_keyword

df.to_csv("1024170304_faq_data.csv", index=False)

print(df)
print("CSV file saved")

Enter new keyword: what is the annual fee
                                      question  \
0                       what is the annual fee
1                        how to reset password
2                  what are your working hours
3                        how can i pay the fee
4  how do i update my registered mobile number

                                              answer  \
0                          The annual fee is Rs 500.
1                   Go to Settings > Reset Password.
2                          We are open 9 AM to 5 PM.
3         You can pay via UPI, card, or net banking.
4  You can update your registered mobile number f...

                                       keywords category
0  fee cost price charge what is the annual fee  billing
1                          password reset login  account
2                        hours timing open time  general
3                           pay payment upi fee  billing
4                  mobile number account update  account
CSV file saved

In [8]:
category_count = df.groupby("category").size()

print("Number of FAQ entries per category:")
print(category_count)

Number of FAQ entries per category:
category
account    2
billing    2
general    1
dtype: int64

In [9]:
def scoring(query,df):
  questions = [sent.lower().split() for sent in df['question']]
  actual = query.lower().split()
  order = []
  for i in range(len(questions)):
    cnt = 0
    for w in actual:
      if(w in questions[i]):
        cnt+=1
    order.append(cnt)
  ans ={}
  for i in range(len(order)):
        if order[i] not in ans:
            ans[order[i]] = []

        ans[order[i]].append(df['question'][i])
  max_score = max(order)
  print("Highest score:", max_score)
  print("Matching questions:")
  for question in ans[max_score]:
      print(question)

  return ans

In [10]:

print("Please enter a query")
query = input()
ranked_FAQ = scoring(query,df)
print("Here are FAQ's in sorted order -> (increasing order of matching)")
print(ranked_FAQ)

Please enter a query
fees
Highest score: 0
Matching questions:
what is the annual fee
how to reset password
what are your working hours
how can i pay the fee
how do i update my registered mobile number
Here are FAQ's in sorted order -> (increasing order of matching)
{0: ['what is the annual fee', 'how to reset password', 'what are your working hours', 'how can i pay the fee', 'how do i update my registered mobile number']}

In [11]:

print("Please enter a query")
query = input()
ranked_FAQ = scoring(query,df)
print("Here are FAQ's in sorted order -> (increasing order of matching)")
print(ranked_FAQ)

Please enter a query
password
Highest score: 1
Matching questions:
how to reset password
Here are FAQ's in sorted order -> (increasing order of matching)
{0: ['what is the annual fee', 'what are your working hours', 'how can i pay the fee', 'how do i update my registered mobile number'], 1: ['how to reset password']}