<a href="https://colab.research.google.com/github/mukul2508/UCS420_MUKUL-_BANSAL_1024170294/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
data={
    'Tid':range(1,11),
    'Refund':['Yes','No','No','Yes','No','No','Yes','No','No','No'],
    'Marital Status':['Single','Married','Single','Married','Divorced','Married','Divorced','Single','Married','Single'],
    'Taxable Income':['125k','100k','70k','120k','95k','60k','220k','85k','75k','90k'],
    'Cheat':['No','No','No','No','Yes','No','No','Yes','No','Yes']
}

In [2]:
df=pd.DataFrame(data)
df

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125k    No
1    2     No        Married           100k    No
2    3     No         Single            70k    No
3    4    Yes        Married           120k    No
4    5     No       Divorced            95k   Yes
5    6     No        Married            60k    No
6    7    Yes       Divorced           220k    No
7    8     No         Single            85k   Yes
8    9     No        Married            75k    No
9   10     No         Single            90k   Yes

In [3]:
df.iloc[[0,4,7,8]]

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125k    No
4    5     No       Divorced            95k   Yes
7    8     No         Single            85k   Yes
8    9     No        Married            75k    No

In [4]:
df.iloc[3:8]

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120k    No
4    5     No       Divorced            95k   Yes
5    6     No        Married            60k    No
6    7    Yes       Divorced           220k    No
7    8     No         Single            85k   Yes

In [5]:
df.iloc[4:9,2:5]

  Marital Status Taxable Income Cheat
4       Divorced            95k   Yes
5        Married            60k    No
6       Divorced           220k    No
7         Single            85k   Yes
8        Married            75k    No

In [6]:
df.iloc[:,1:4]

  Refund Marital Status Taxable Income
0    Yes         Single           125k
1     No        Married           100k
2     No         Single            70k
3    Yes        Married           120k
4     No       Divorced            95k
5     No        Married            60k
6    Yes       Divorced           220k
7     No         Single            85k
8     No        Married            75k
9     No         Single            90k

In [11]:
df1=pd.read_csv('Iris.csv')
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [12]:
df1.drop(index=4,columns=df1.columns[3],inplace=True)

In [13]:
df1

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

In [14]:
df2=pd.read_csv('employees.csv')
df2

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [15]:
df2.shape

(5, 10)

In [16]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [17]:
df2.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [20]:
df2.head(5)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [21]:

df2.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [23]:
mean_sal=df2['Salary'].mean()
mean_sal

np.float64(60000.0)

In [25]:
df2.Bonus.sum()

np.int64(27500)

In [26]:
df2['Age'].min()

28

In [27]:
df2['Rating'].max()

4.7

In [28]:
df2.sort_values(by=['Salary'],ascending=False,inplace=True)
df2

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [38]:
df2['Performance']=df2['Rating'].apply(lambda x:'excellent' if x>4.5
 else 'good'if x>=4
 else 'average'
 )
df2.head()

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Tax,Performance
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,7000.0,good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,6500.0,average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,6000.0,average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,5500.0,excellent
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,5000.0,good

In [29]:
df2.isnull().sum()

Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
dtype: int64

In [31]:

df2.rename(columns={"Employee_ID": "ID"},inplace=True)
print(df2.columns)

Index(['ID', 'Name', 'Department', 'Age', 'Salary', 'Years_of_Experience',
       'Joining_Date', 'Gender', 'Bonus', 'Rating'],
      dtype='object')

In [32]:
df2[df2['Years_of_Experience']>5]

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [33]:
df2[df2['Department']=='IT']

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8

In [34]:
df2['Tax']=df2['Salary'].apply(lambda x:x*0.1)
df2

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Tax
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,6500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,6000.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,5500.0
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,5000.0

In [39]:
df2.to_csv("employee_new.csv", index=False)
import os
print(os.path.exists("employee_new.csv"))

True